(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["components/dp-search/dp-search"],{"6d4a":function(a,t,e){"use strict";var r;e.d(t,"b",(function(){return n})),e.d(t,"c",(function(){return o})),e.d(t,"a",(function(){return r}));var n=function(){var a=this,t=a.$createElement,e=(a._self._c,(!a.params.openmore||a.params.openmore<=0)&&1==a.params.btn?a.t("color1"):null);a.$mp.data=Object.assign({},{$root:{m0:e}})},o=[]},"79ba":function(a,t,e){"use strict";var r=e("9fa7"),n=e.n(r);n.a},"8f01":function(a,t,e){"use strict";e.r(t);var r=e("6d4a"),n=e("aa14");for(var o in n)"default"!==o&&function(a){e.d(t,a,(function(){return n[a]}))}(o);e("79ba");var u,l=e("f0c5"),d=Object(l["a"])(n["default"],r["b"],r["c"],!1,null,null,null,!1,r["a"],u);t["default"]=d.exports},"8f4f":function(a,t,e){"use strict";(function(a){Object.defineProperty(t,"__esModule",{value:!0}),t.default=void 0;var e=getApp(),r={data:function(){return{pre_url:getApp().globalData.pre_url,data_index:0,data_name:"",data_placeholder:"",data_hrefurl:"",keyword:""}},props:{params:{bid:{default:0}},data:{}},mounted:function(){var a=this;console.log(a.params),a.data&&(a.data_name=a.data[0]["title1"],a.data_placeholder=a.data[0]["title2"],a.data_hrefurl=a.data[0]["hrefurl"],console.log(a.data[0]["hrefurl"]))},methods:{searchgoto:function(a){var t=this,r=t.keyword,n=a.currentTarget.dataset.url;n.indexOf("?")>0?n+="&keyword="+r:n+="?keyword="+r;var o=a.currentTarget.dataset.opentype;e.goto(n,o)},dataChange:function(a){var t=this,e=t.data,r=a.detail.value;t.data_index=r,t.data_name=e[r]["title1"],t.data_placeholder=e[r]["title2"],t.data_hrefurl=e[r]["hrefurl"]},inputKeyword:function(a){var t=this;t.keyword=a.detail.value},scanQRCode:function(t){"h5"==e.globalData.platform||"mp"==e.globalData.platform||a.scanCode({success:function(a){console.log(a);var t=a.result;t?e.post("ApiShop/scanCodeSearchGoods",{specs_number:t},(function(a){1==a.status?e.goto("pages/shop/product?id="+a.product_id):e.alert(a.msg)})):e.alert("请扫描正确的商品码")},fail:function(a){console.error("扫码失败：",a)}})}}};t.default=r}).call(this,e("a821")["default"])},"9fa7":function(a,t,e){},aa14:function(a,t,e){"use strict";e.r(t);var r=e("8f4f"),n=e.n(r);for(var o in r)"default"!==o&&function(a){e.d(t,a,(function(){return r[a]}))}(o);t["default"]=n.a}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'components/dp-search/dp-search-create-component',
    {
        'components/dp-search/dp-search-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('a821')['createComponent'](__webpack_require__("8f01"))
        })
    },
    [['components/dp-search/dp-search-create-component']]
]);
