(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["components/dp-video/dp-video"],{"0b2b":function(t,a,e){},"2cae":function(t,a,e){"use strict";var i;e.d(a,"b",(function(){return n})),e.d(a,"c",(function(){return r})),e.d(a,"a",(function(){return i}));var n=function(){var t=this,a=t.$createElement,e=(t._self._c,(.3*t.Height).toFixed(2));t.$mp.data=Object.assign({},{$root:{g0:e}})},r=[]},4196:function(t,a,e){"use strict";e.r(a);var i=e("776a"),n=e.n(i);for(var r in i)"default"!==r&&function(t){e.d(a,t,(function(){return i[t]}))}(r);a["default"]=n.a},"776a":function(t,a,e){"use strict";(function(t){Object.defineProperty(a,"__esModule",{value:!0}),a.default=void 0;var e=getApp(),i={props:{params:{},data:{}},data:function(){return{Height:"",pre_url:getApp().globalData.pre_url,hastabbar:!1}},mounted:function(){var a=this;t.getSystemInfo({success:function(t){a.Height=t.windowHeight}});var i=getCurrentPages(),n=i[i.length-1],r="/"+(n.route?n.route:n.__route__);if("baidu"==e.globalData.platform)var u=n.options;else u=n.$vm.opt;u&&u.id?r+="?id="+u.id:u&&u.cid?r+="?cid="+u.cid:u&&u.gid?r+="?gid="+u.gid:u&&u.bid&&(r+="?bid="+u.bid);for(var o=JSON.parse(JSON.stringify(e.globalData.initdata.menudata)),d=o["list"],c=0;c<d.length;c++)d[c]["pagePath"]==r&&(this.hastabbar=!0);if(0==this.hastabbar){var l=JSON.parse(JSON.stringify(e.globalData.initdata.menu2data));if(l.length>0)for(var c in l)u&&u.bid&&(l[c].indexurl=l[c].indexurl.replace("[bid]",u.bid)),l[c].indexurl==r&&(this.hastabbar=!0)}}};a.default=i}).call(this,e("5486")["default"])},b8a7:function(t,a,e){"use strict";var i=e("0b2b"),n=e.n(i);n.a},cbd4:function(t,a,e){"use strict";e.r(a);var i=e("2cae"),n=e("4196");for(var r in n)"default"!==r&&function(t){e.d(a,t,(function(){return n[t]}))}(r);e("b8a7");var u,o=e("f0c5"),d=Object(o["a"])(n["default"],i["b"],i["c"],!1,null,null,null,!1,i["a"],u);a["default"]=d.exports}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'components/dp-video/dp-video-create-component',
    {
        'components/dp-video/dp-video-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('5486')['createComponent'](__webpack_require__("cbd4"))
        })
    },
    [['components/dp-video/dp-video-create-component']]
]);
