(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["components/popmsg/popmsg"],{"0929":function(t,a,i){"use strict";i.r(a);var e=i("aac5"),o=i("a84a");for(var n in o)"default"!==n&&function(t){i.d(a,t,(function(){return o[t]}))}(n);i("a059");var s,u=i("f0c5"),c=Object(u["a"])(o["default"],e["b"],e["c"],!1,null,null,null,!1,e["a"],s);a["default"]=c.exports},"5cd96":function(t,a,i){},a059:function(t,a,i){"use strict";var e=i("5cd96"),o=i.n(e);o.a},a84a:function(t,a,i){"use strict";i.r(a);var e=i("d0bd"),o=i.n(e);for(var n in e)"default"!==n&&function(t){i.d(a,t,(function(){return e[t]}))}(n);a["default"]=o.a},aac5:function(t,a,i){"use strict";var e;i.d(a,"b",(function(){return o})),i.d(a,"c",(function(){return n})),i.d(a,"a",(function(){return e}));var o=function(){var t=this,a=t.$createElement;t._self._c},n=[]},d0bd:function(t,a,i){"use strict";(function(t){Object.defineProperty(a,"__esModule",{value:!0}),a.default=void 0;var i={props:{navigationHieght:{default:0}},data:function(){return{popmsg:0,logo:"",title:"",desc:"",tourl:"",duration:0,pre_url:getApp().globalData.pre_url,homeNavigationCustom:getApp().globalData.homeNavigationCustom}},methods:{open:function(a){var i=this;console.log(a),"tokefu"==a.type?(this.logo=a.data.headimg,this.title=a.data.nickname+" 发来消息",this.desc=a.data.content,this.tourl="/admin/kefu/message?mid="+a.data.mid):"tokehu"==a.type?(this.logo=a.data.uheadimg,this.title=a.data.unickname+" 发来消息",this.desc=a.data.content,this.tourl="/pages/kefu/index?bid="+a.data.bid):"peisong"==a.type?(this.logo="",this.title=a.data.title,this.desc=a.data.desc,1==a.data.type?this.tourl="/activity/peisong/orderlist":this.tourl="/activity/peisong/dating"):(this.logo="",this.title=a.data.title,this.desc=a.data.desc,this.tourl=a.data.url),this.popmsg=1;var e=t.createInnerAudioContext();e.autoplay=!0,e.src=this.pre_url+"/static/chat/default.mp3",e.onPlay((function(){console.log("开始播放")})),0!==this.duration&&(clearTimeout(this.popuptimer),this.popuptimer=setTimeout((function(){i.close()}),this.duration))},close:function(){this.popmsg=2,clearTimeout(this.popuptimer)},gotourl:function(t){this.close(),this.goto(t)}}};a.default=i}).call(this,i("5486")["default"])}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'components/popmsg/popmsg-create-component',
    {
        'components/popmsg/popmsg-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('5486')['createComponent'](__webpack_require__("0929"))
        })
    },
    [['components/popmsg/popmsg-create-component']]
]);
