(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["components/wxxieyi/wxxieyi"],{"0423":function(t,n,e){"use strict";e.r(n);var i=e("a125"),o=e("6a68");for(var a in o)"default"!==a&&function(t){e.d(n,t,(function(){return o[t]}))}(a);e("b872");var r,c=e("f0c5"),u=Object(c["a"])(o["default"],i["b"],i["c"],!1,null,null,null,!1,i["a"],r);n["default"]=u.exports},"19cb":function(t,n,e){"use strict";(function(t){Object.defineProperty(n,"__esModule",{value:!0}),n.default=void 0;var e=getApp(),i={data:function(){return{needAuthorization:!1,privacyContractName:"",resolvePrivacyAuthorization:""}},mounted:function(){var t=this;wx.onNeedPrivacyAuthorization((function(n,e){t.getPrivacySetting(),t.resolvePrivacyAuthorization=n}))},methods:{getPrivacySetting:function(){var n=this;wx.getPrivacySetting({success:function(e){e.needAuthorization&&(t.hideLoading(),n.needAuthorization=e.needAuthorization,n.privacyContractName=e.privacyContractName)},fail:function(t){e.error(t)}})},handleAgreePrivacyAuthorization:function(){this.needAuthorization=!1,this.resolvePrivacyAuthorization({buttonId:"agree-btn",event:"agree"}),setTimeout((function(){e.globalData.copyinfo&&e.copy(e.globalData.copyinfo)}),1e3)},handleOpenPrivacyContract:function(){wx.openPrivacyContract()}}};n.default=i}).call(this,e("543d")["default"])},"6a68":function(t,n,e){"use strict";e.r(n);var i=e("19cb"),o=e.n(i);for(var a in i)"default"!==a&&function(t){e.d(n,t,(function(){return i[t]}))}(a);n["default"]=o.a},a125:function(t,n,e){"use strict";var i;e.d(n,"b",(function(){return o})),e.d(n,"c",(function(){return a})),e.d(n,"a",(function(){return i}));var o=function(){var t=this,n=t.$createElement,e=(t._self._c,t.needAuthorization?t.t("color1"):null),i=t.needAuthorization&&void 0!=e?t.t("color1"):null;t.$mp.data=Object.assign({},{$root:{m0:e,m1:i}})},a=[]},b872:function(t,n,e){"use strict";var i=e("c3d4"),o=e.n(i);o.a},c3d4:function(t,n,e){}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'components/wxxieyi/wxxieyi-create-component',
    {
        'components/wxxieyi/wxxieyi-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("0423"))
        })
    },
    [['components/wxxieyi/wxxieyi-create-component']]
]);
