(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["components/wxxieyi/wxxieyi"],{"0423":function(t,n,e){"use strict";e.r(n);var o=e("a125"),a=e("6a68");for(var i in a)"default"!==i&&function(t){e.d(n,t,(function(){return a[t]}))}(i);e("b872");var r,c=e("f0c5"),u=Object(c["a"])(a["default"],o["b"],o["c"],!1,null,null,null,!1,o["a"],r);n["default"]=u.exports},"19cb":function(t,n,e){"use strict";(function(t,e){Object.defineProperty(n,"__esModule",{value:!0}),n.default=void 0;var o=getApp(),a={data:function(){return{needAuthorization:!1,privacyContractName:"",resolvePrivacyAuthorization:""}},mounted:function(){},methods:{getPrivacySetting:function(){var n=this;t.getPrivacySetting({success:function(t){t.needAuthorization&&(e.hideLoading(),n.needAuthorization=t.needAuthorization,n.privacyContractName=t.privacyContractName)},fail:function(t){o.error(t)}})},handleAgreePrivacyAuthorization:function(){this.needAuthorization=!1,this.resolvePrivacyAuthorization({buttonId:"agree-btn",event:"agree"}),setTimeout((function(){o.globalData.copyinfo&&o.copy(o.globalData.copyinfo)}),1e3)},handleOpenPrivacyContract:function(){t.openPrivacyContract()}}};n.default=a}).call(this,e("f266")["default"],e("f266")["default"])},"6a68":function(t,n,e){"use strict";e.r(n);var o=e("19cb"),a=e.n(o);for(var i in o)"default"!==i&&function(t){e.d(n,t,(function(){return o[t]}))}(i);n["default"]=a.a},a125:function(t,n,e){"use strict";var o;e.d(n,"b",(function(){return a})),e.d(n,"c",(function(){return i})),e.d(n,"a",(function(){return o}));var a=function(){var t=this,n=t.$createElement,e=(t._self._c,t.needAuthorization?t.t("color1"):null),o=t.needAuthorization&&void 0!=e?t.t("color1"):null;t.$mp.data=Object.assign({},{$root:{m0:e,m1:o}})},i=[]},b872:function(t,n,e){"use strict";var o=e("c3d4"),a=e.n(o);a.a},c3d4:function(t,n,e){}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'components/wxxieyi/wxxieyi-create-component',
    {
        'components/wxxieyi/wxxieyi-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('f266')['createComponent'](__webpack_require__("0423"))
        })
    },
    [['components/wxxieyi/wxxieyi-create-component']]
]);
