(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["components/dp-collage/dp-collage"],{5153:function(r,o,t){"use strict";var l=t("d1ba"),a=t.n(l);a.a},5880:function(r,o,t){"use strict";Object.defineProperty(o,"__esModule",{value:!0}),o.default=void 0;var l={data:function(){return{pre_url:getApp().globalData.pre_url}},props:{params:{},data:{}}};o.default=l},"6bac":function(r,o,t){"use strict";var l;t.d(o,"b",(function(){return a})),t.d(o,"c",(function(){return c})),t.d(o,"a",(function(){return l}));var a=function(){var r=this,o=r.$createElement,t=(r._self._c,"0"!=r.params.showprice?r.t("color1"):null),l="1"==r.params.style||"2"==r.params.style||"3"==r.params.style?r.__map(r.data,(function(o,t){var l=r.__get_orig(o),a=o.collage_type?null:r.t("color1rgb"),c=o.collage_type?null:r.t("color1");return{$orig:l,m1:a,m2:c}})):null,a="0"!=r.params.showprice?r.t("color1"):null,c=r.t("color1rgb"),n=r.t("color1"),e="0"!=r.params.showprice?r.t("color1"):null,u=r.t("color1rgb"),m=r.t("color1"),s=r.t("color1rgb"),i=r.t("color1"),p=r.t("color1rgb"),f=r.t("color1"),b=r.t("color1rgb"),d=r.t("color1"),g=r.t("color1rgb"),v=r.t("color1rgb"),_=r.t("color1"),y=r.t("color1rgb"),h=r.t("color1"),w=r.t("color1"),$=r.t("color1"),j=r.t("color1rgb");r.$mp.data=Object.assign({},{$root:{m0:t,l0:l,m3:a,m4:c,m5:n,m6:e,m7:u,m8:m,m9:s,m10:i,m11:p,m12:f,m13:b,m14:d,m15:g,m16:v,m17:_,m18:y,m19:h,m20:w,m21:$,m22:j}})},c=[]},a89d:function(r,o,t){"use strict";t.r(o);var l=t("6bac"),a=t("ee26");for(var c in a)"default"!==c&&function(r){t.d(o,r,(function(){return a[r]}))}(c);t("5153");var n,e=t("f0c5"),u=Object(e["a"])(a["default"],l["b"],l["c"],!1,null,null,null,!1,l["a"],n);o["default"]=u.exports},d1ba:function(r,o,t){},ee26:function(r,o,t){"use strict";t.r(o);var l=t("5880"),a=t.n(l);for(var c in l)"default"!==c&&function(r){t.d(o,r,(function(){return l[r]}))}(c);o["default"]=a.a}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'components/dp-collage/dp-collage-create-component',
    {
        'components/dp-collage/dp-collage-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('5486')['createComponent'](__webpack_require__("a89d"))
        })
    },
    [['components/dp-collage/dp-collage-create-component']]
]);
